--가격이 제일 비싼 식품의 정보 출력하기

--<오답>
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, MAX(PRICE) PRICE
FROM FOOD_PRODUCT
GROUP BY PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY

--만약 max 값이 같은 제품이 여러개인 경우 max()는 해당하는 모든 제품들을 다 보여주는데 limit을 이용하면 가장 큰 하나 밖에 안보여줍니다.

--<정답>

--1.ROWNUM 활용
SELECT *
FROM (
    SELECT *
    FROM FOOD_PRODUCT
    ORDER BY PRICE DESC
)
WHERE ROWNUM = 1;


--2.서브쿼리 활용
SELECT *
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);


--가장 비싼 상품 구하기
SELECT MAX(PRICE) MAX_PRICE
FROM PRODUCT


--최솟값 구하기
--<오답>
--**`ROWNUM`**은 정렬되기 이전에 부여되기 때문에 정렬과는 무관하게 첫 번째 행만 선택됩니다.
SELECT DATETIME FROM ANIMAL_INS  WHERE ROWNUM = 1 ORDER BY DATETIME DESC


--가장 최근 데이터의 날짜를 선택하는 결과
SELECT DATETIME
FROM (
    SELECT DATETIME
    FROM ANIMAL_INS
    ORDER BY DATETIME DESC
) SUB
WHERE ROWNUM = 1;


--<정답>
--1.FETCH FIRST 1 ROWS ONLY  
SELECT DATETIME
FROM ANIMAL_INS
ORDER BY DATETIME
FETCH FIRST 1 ROWS ONLY; —가장 초기 데이터 선택

--2.MIN
SELECT DATETIME
FROM ANIMAL_INS
WHERE DATETIME = (SELECT MIN(DATETIME) FROM ANIMAL_INS );


--동물 수 구하기
SELECT COUNT(*) COUNT FROM ANIMAL_INS --테이블 행 갯수 셈


--중복 제거하기
SELECT COUNT(DISTINCT NAME) AS COUNT --중복제거후 행수세기
FROM ANIMAL_INS 
WHERE NAME IS NOT NULL
