/*
입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리
ANIMAL_INS A
ANIMAL_OUTS B
B.DATETIME - A.DATETIME
*/
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A
INNER JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY B.DATETIME - A.DATETIME DESC
FETCH FIRST 2 ROWS ONLY;