/*
중고 거래 게시물을 3건 이상 등록 
USED_GOODS_BOARD A
USED_GOODS_USER B

SELECT USER_ID, NICKNAME
,CITY ||' '|| STREET_ADDRESS1	||' '|| STREET_ADDRESS2 전체주소
,SUBSTR(TLNO,0,3) || '-' || SUBSTR(TLNO,4,4) || '-' || SUBSTR(TLNO,8,11) 전화번호
FROM USED_GOODS_USER
ORDER BY USER_ID
*/


SELECT USER_ID, NICKNAME
,CITY ||' '|| STREET_ADDRESS1	||' '|| STREET_ADDRESS2 전체주소
,SUBSTR(TLNO,0,3) || '-' || SUBSTR(TLNO,4,4) || '-' || SUBSTR(TLNO,8,11) 전화번호
FROM USED_GOODS_USER
WHERE USER_ID IN(
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
)
ORDER BY USER_ID DESC
