/*
아직 입양을 못 간 동물 중, 가장 오래 보호소에 있었던 동물 3마리
ANIMAL_INS A ANIMAL_OUTS B

SELECT A.NAME, A.DATETIME
    FROM ANIMAL_INS A
 JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY A.DATETIME
*/

SELECT A.NAME, A.DATETIME
    FROM ANIMAL_INS A
    LEFT JOIN (
        SELECT * FROM ANIMAL_OUTS
    ) B 
    ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.DATETIME IS NULL
ORDER BY A.DATETIME 
FETCH FIRST 3 ROWS ONLY


