/*
생산일자가 2022년 5월인 식품들의 총매출 
FOOD_PRODUCT A
FOOD_ORDER B



SUM(A.PRICE*B.AMOUNT) TOTAL_SALES

A.PRODUCT_ID, A.PRODUCT_NAME, B.TOTAL_SALES

SELECT SUM(A.PRICE*B.AMOUNT) TOTAL_SALES
        FROM FOOD_ORDER B
    GROUP BY B.PRODUCT_ID

SELECT A.PRODUCT_ID, A.PRODUCT_NAME, B.TOTAL_SALES
    FROM FOOD_PRODUCT A
INNER JOIN(
        
    
    
        )B
ON A.PRODUCT_ID = B.PRODUCT_ID
*/
SELECT T1.PRODUCT_ID, T1.PRODUCT_NAME, T2.TOTAL_SALES
    FROM FOOD_PRODUCT T1
    INNER JOIN 
    (
    SELECT A.PRODUCT_ID, SUM(A.PRICE*B.AMOUNT) TOTAL_SALES
        FROM FOOD_PRODUCT A
    INNER JOIN FOOD_ORDER B
    ON A.PRODUCT_ID = B.PRODUCT_ID
    WHERE TO_CHAR(B.PRODUCE_DATE,'YYYY-MM')='2022-05'
    GROUP BY A.PRODUCT_ID
        )T2
    ON T1.PRODUCT_ID = T2.PRODUCT_ID
ORDER BY T2.TOTAL_SALES DESC, T1.PRODUCT_ID


