
SELECT A.USER_ID, A.NICKNAME, T1.TOTAL_SALES
FROM USED_GOODS_USER A
INNER JOIN (
    SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS='DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
    )T1
ON A.USER_ID =T1.WRITER_ID
ORDER BY TOTAL_SALES