/*
USED_GOODS_BOARD A 
USED_GOODS_USER B
B.USER_ID, B.NICKNAME, TOTAL_SALES

A.WRITER_ID = B.USER_ID
STATUS='DONE'

SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING SUM(PRICE) >=700000
*/

SELECT A.USER_ID, A.NICKNAME, B.TOTAL_SALES
    FROM USED_GOODS_USER A
INNER JOIN (
    SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
        FROM USED_GOODS_BOARD
    WHERE STATUS='DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >=700000
) B ON A.USER_ID=B.WRITER_ID
ORDER BY B.TOTAL_SALES

