/*
리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
MEMBER_PROFILE A
REST_REVIEW B

A.MEMBER_NAME, B.REVIEW_TEXT, B.REVIEW_DATE
*/

--SELECT A.MEMBER_NAME, B.
--FROM MEMBER_PROFILE A

SELECT A.MEMBER_NAME, B.REVIEW_TEXT, B.REVIEW_DATE
FROM MEMBER_PROFILE A
INNER JOIN (
    SELECT T2.MEMBER_ID, T2.REVIEW_TEXT, TO_CHAR(T2.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
    FROM REST_REVIEW T2
    INNER JOIN (SELECT MEMBER_ID
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY COUNT(*) DESC
            FETCH FIRST 1 ROW ONLY
        ) T1
    ON T2.MEMBER_ID = T1.MEMBER_ID
) B
ON A.MEMBER_ID = B.MEMBER_ID
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT

   