/*

MONTH, CAR_ID, RECORDS

CAR_RENTAL_COMPANY_RENTAL_HISTORY 

대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상


--TO_CHAR(START_DATE,'YYYY-MM') = '2022-08'  TO_CHAR(END_DATE,'YYYY-MM') ='2022-10'

--SELECT CAR_ID
*/

SELECT TO_NUMBER(TO_CHAR(A.START_DATE,'MM')) MONTH, A.CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
INNER JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)B
ON A.CAR_ID = B.CAR_ID
WHERE A.START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
GROUP BY TO_NUMBER(TO_CHAR(A.START_DATE,'MM')), A.CAR_ID
ORDER BY MONTH, CAR_ID DESC 




