/*
CAR_RENTAL_COMPANY_CAR 
CAR_RENTAL_COMPANY_RENTAL_HISTORY

 자동차 종류가 '세단'인 자동차들 중 
 10월에 대여를 시작한 기록이 있는 자동차
 GROUP BY A.CAR_TYPE
ORDER BY CAR_ID



SELECT CAR_TYPE
FROM CAR_RENTAL_COMPANY_CAR A
*/

SELECT T1.CAR_ID
FROM(
    SELECT A.CAR_TYPE, A.CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR A
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
    WHERE A.CAR_TYPE = '세단'AND TO_CHAR(B.START_DATE,'YYYY-MM') LIKE '%2022-10%'
)T1
GROUP BY T1.CAR_ID
ORDER BY T1.CAR_ID DESC






