/*
동차 종류가 '세단'인 자동차들 중 
10월에 대여를 시작한 기록이 있는 자동차 ID
자동차 ID 리스트는 중복이 없어야 하며, 
자동차 ID를 기준으로 내림차순 정렬
*/



SELECT DISTINCT(A.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
INNER JOIN(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR 
    WHERE CAR_TYPE='세단'    
)T1
ON A.CAR_ID =T1.CAR_ID
WHERE TO_CHAR(START_DATE,'MM')='10'
ORDER BY CAR_ID DESC 