SELECT 
    '/home/grep/src/' || A.BOARD_ID || '/' || A.FILE_ID || A.FILE_NAME || A.FILE_EXT AS FILE_PATH
FROM USED_GOODS_FILE A
INNER JOIN (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
) B
ON A.BOARD_ID = B.BOARD_ID
ORDER BY A.FILE_ID DESC;
